name: 'ci'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set node version to 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - run: npm ci

      - name: Run lint
        run: npm run lint

  format-job:
    needs: lint-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set node version to 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - run: npm ci

      - name: Run format code
        run: npm run format
    
  unit-test:
    needs: format-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set node version to 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - run: npm ci

      - name: Run unit test
        run: npm run test:unit