name: 'deploy docker'

on:
  push:
    tags:
      - "*"

jobs:

  release-docker-image-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{ github.event.repository.name }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  auto-deploy-docker-job:
    needs: release-docker-image-job
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: '159.223.41.181'
        username: 'root'
        password: '$Admin_1jj395qu'
        port: '22'
        script: whoami