name: 'deploy docker'

on:
  push:
    tags:
      - "*"

jobs:

  release-docker-image-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{ github.event.repository.name }}
          registry: ghcr.io
          username: ${{ github.event.repository }}
          password: ${{ secrets.GITHUB_TOKEN }}

      