name: 'deploy'

on:
  push:
    tags:
      - "*"
jobs:
  build-production-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set node version to 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - run: npm ci

      - name: Run build for production
        run: npm run build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-production
          path: dist  

  deploy-production-job:
    runs-on: ubuntu-latest
    steps:
    #  - uses: actions/checkout@v4

    #   - name: Set node version to 18
    #     uses: actions/setup-node@v3
    #     with:
    #       node-version: '18.x'
    #       cache: 'npm'

    #   - run: npm ci

    #   - name: Run build for production
    #     run: npm run build

      - name: Download production artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-production
          path: dist 
        
      - run: ls dist